# https://github.com/docker-library/python
FROM docker.io/library/python:slim-bookworm

# Update OS packages and install OS level dependencies if required
RUN set -o errexit \
    set -o nounset \
    set -o pipefail \
    set -o xtrace \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get upgrade --assume-yes --no-install-recommends \
    && apt-get clean \
    && apt-get purge --assume-yes --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && apt-get check \
    && rm -rf /var/lib/apt/lists/*

# Switch to non-root user
RUN set -o errexit \
    set -o nounset \
    set -o pipefail \
    set -o xtrace \
    && useradd --create-home appuser
USER appuser
WORKDIR /home/appuser

# Install Python tools
RUN set -o errexit \
    set -o nounset \
    set -o pipefail \
    set -o xtrace \
    && python -m pip install --user pipx \
    && python -m pipx ensurepath \
    && pipx run nox --version
