# https://github.com/docker-library/python
FROM docker.io/library/python:slim-bookworm

# Update OS packages and install OS level dependencies if required
RUN set -o errexit \
    set -o nounset \
    set -o pipefail \
    set -o xtrace \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get upgrade --assume-yes --no-install-recommends \
    && apt-get clean \
    && apt-get purge --assume-yes --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && apt-get check \
    && rm -rf /var/lib/apt/lists/*

# Switch to non-root user
# TODO: Test --no-log-init
RUN set -o errexit \
    set -o nounset \
    set -o pipefail \
    set -o xtrace \
    && useradd --create-home --no-log-init appuser
USER appuser
WORKDIR /home/appuser

# Install Python tools
# Use this to make the container smaller:
#    pip...  --no-cache-dir \
#    && rm -rf $(python -m pip cache dir) \
RUN set -o errexit \
    set -o nounset \
    set -o pipefail \
    set -o xtrace \
    && python -m pip install \
        --disable-pip-version-check \
        --upgrade \
        --user \
            pipx \
    && python -m pip check \
    && python -m pipx ensurepath \
    && python -m pipx run nox --version

# Start with bash instead of Python repl.
CMD /bin/bash
