[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# See more keys and their definitions at https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

[project]
name = "demo"
version = "0.1.0"

[project.optional-dependencies]
test = ["pytest"]
lint = ["black", "ruff"]
